### ISSUE TITLE
Spurious errors with unique rules

### ISSUE THREAD

**Issue by stropitek** [dotansimha/graphql-eslint#296]
I am getting spurious errors when running a few of the unique rules

Repro: https://github.com/zakodium/eslint-config-graphql (the `failing-rules` branch) with `npm run test`

You can see the 5 unique rules that fail in this diff: [here](https://github.com/zakodium/eslint-config-graphql/pull/6/files)

The tested schema / document files are [here](https://github.com/zakodium/eslint-config-graphql/tree/failing-rules/test), the error output can be seen [here](https://github.com/zakodium/eslint-config-graphql/runs/1828801064)

It's running graphql-eslint v0.8.0

I hope this helps and I'm not missing anything obvious

**Comment by dotansimha** [comment]
Fixed, the issue was in `graphql-eslint/unique-type-names`. Will cut a release very soon!

**Comment by dotansimha** [comment]
Fixed in `v1.0.0`! 🎉

**Comment by stropitek** [comment]
there are no false positives for `graphql-eslint/unique-type-names` anymore. Thanks!

Other rules are still failing though, should I open a separate issue for each one of them?

https://github.com/zakodium/eslint-config-graphql/runs/2618345467

I don't think you can see the action logs so here is an image:

![image](https://user-images.githubusercontent.com/4118690/118783459-5fadec80-b88f-11eb-98fe-436a156248fb.png)

**Comment by dotansimha** [comment]
> there are no false positives for `graphql-eslint/unique-type-names` anymore. Thanks!
> 
> Other rules are still failing though, should I open a separate issue for each one of them?
> 
> https://github.com/zakodium/eslint-config-graphql/runs/2618345467
> 
> I don't think you can see the action logs so here is an image:
> 
> ![image](https://user-images.githubusercontent.com/4118690/118783459-5fadec80-b88f-11eb-98fe-436a156248fb.png)

I think I managed to fix that in: https://github.com/dotansimha/graphql-eslint/pull/433 , can you please try `@graphql-eslint/eslint-plugin@1.0.1-alpha-a5bff45.0`?

**Comment by stropitek** [comment]
I now have 2 other failures with `@graphql-eslint/eslint-plugin@1.0.1-alpha-a5bff45.0`, but the two rules failing above pass. I'm not sure if those 2 other rules were failing before or not, I might have have taken a partial screenshot, and I'm unable to see github action logs at the moment to check that.

![image](https://user-images.githubusercontent.com/4118690/118792332-da7b0580-b897-11eb-8185-5fd9a63e5a85.png)

**Comment by dotansimha** [comment]
> I now have 2 other failures with `@graphql-eslint/eslint-plugin@1.0.1-alpha-a5bff45.0`, but the two rules failing above pass. The 2 other failures were there before but I did a mistake when taking the screenshot above.
> 
> ![image](https://user-images.githubusercontent.com/4118690/118792332-da7b0580-b897-11eb-8185-5fd9a63e5a85.png)

Thank you for the quick feedback! It seems like it's the same file, so maybe just an issue with the comparison of the paths. You are using Windows, right? seems like incompatibility with the `/` and `\` in the paths.

**Comment by stropitek** [comment]
You are right! The tests are now passing on github actions, but not on my windows machine.

Although the tests are now passing, I'm getting false negatives (tests passing when they should fail). I'm defining the same type twice and my tests are still passing. 

See my 2 schema files defining the same type:
https://github.com/zakodium/eslint-config-graphql/tree/failing-rules/test/schema

Does this rule only work if the types are defined in the same file?

**Comment by dotansimha** [comment]
@stropitek can you please try `@graphql-eslint/eslint-plugin@1.0.1-alpha-e98cae7.0`? It should fix Windows issues. 

> Does this rule only work if the types are defined in the same file?

For now, yeah, because this is how this GraphQL validation rule works. Maybe we can extend its functionality to test it against the loaded schema, but it might be more tricky. If you want this - feel free to open a new issue and we'll consider that! :)

**Comment by dotansimha** [comment]
Awesome, thanks again for the quick feedback!

I released a new version `v1.0.1` with these fixes and a few more by @B2o5T :)
